#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin (adapted for no-source-checkout env).
# Build: compile src/ → lib/ with the plugin-local tsc.
# Compile-time type deps (cordis / @types/node) are junction-linked from the
# profile node_modules registry (same registry the injector links runtime deps from).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
PROFILE_NM="$DSH_HOME/profiles/node_modules"

TSC="node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC (run: npm i -D typescript)" >&2
  exit 1
fi

if [ -d "$PROFILE_NM" ]; then
  # 本机路径：类型依赖从 profile node_modules 注册表 junction 链接（与注入器运行时一致）
  link_pkg() {
    local link="$1"
    local target="$2"
    node -e "
      const fs = require('fs');
      const path = require('path');
      const link = path.resolve(process.argv[1]);
      const target = path.resolve(process.argv[2]);
      fs.rmSync(link, { recursive: true, force: true });
      fs.mkdirSync(path.dirname(link), { recursive: true });
      fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
    " "$link" "$target"
  }
  echo "=== Linking compile-time deps (registry: $PROFILE_NM) ==="
  mkdir -p node_modules/@deepseek-ai
  link_pkg node_modules/cordis "$PROFILE_NM/@deepseek-ai/cordis"
  link_pkg node_modules/@types/node "$PROFILE_NM/@types/node"
else
  # CI / 裸环境回退：直接从 npm 安装编译期类型依赖。
  # 注意用 @deepseek-ai/cordis（DSH 的 cordis fork，导出 Context）；
  # 官方 cordis 4.0.0-rc 无 Context 导出，会编译失败。
  # --legacy-peer-deps：规避 npm Arborist edgesOut 空指针崩溃（CI 实测踩坑）
  echo "=== Profile registry not found, installing compile-time deps from npm ==="
  mkdir -p node_modules/@deepseek-ai
  npm install --no-save --legacy-peer-deps "@deepseek-ai/cordis@>=4.0.0 <5" "@types/node@>=24 <27"
  rm -rf node_modules/cordis
  ln -s @deepseek-ai/cordis node_modules/cordis
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="
