#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin (adapted for no-source-checkout env).
# Build: compile src/ → lib/ with the plugin-local tsc.
# Compile-time type deps (cordis / @types/node) are junction-linked from the
# profile node_modules registry (same registry the injector links runtime deps from).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
PROFILE_NM="$DSH_HOME/profiles/node_modules"

if [ ! -d "$PROFILE_NM" ]; then
  echo "build: cannot locate the profile node_modules registry at $PROFILE_NM" >&2
  exit 1
fi

TSC="node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC (run: npm i -D typescript)" >&2
  exit 1
fi

link_pkg() {
  local link="$1"
  local target="$2"
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "$link" "$target"
}

echo "=== Linking compile-time deps (registry: $PROFILE_NM) ==="
mkdir -p node_modules/@deepseek-ai
link_pkg node_modules/cordis "$PROFILE_NM/@deepseek-ai/cordis"
link_pkg node_modules/@types/node "$PROFILE_NM/@types/node"

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="
